name: cms-template

services:
  proxy:
    image: jeff2266.engineering/${COMPOSE_PROJECT_NAME}-proxy:latest
    build:
      context: ./proxy/
    depends_on:
      frontend:
        condition: service_started
        restart: true
      backend:
        condition: service_started
        restart: true
    ports:
      - 80:80
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:?}
  frontend:
    image: jeff2266.engineering/${COMPOSE_PROJECT_NAME}-frontend:latest
    build:
      context: ./frontend
  backend:
    image: jeff2266.engineering/${COMPOSE_PROJECT_NAME}-backend:latest
    build:
      context: ./backend
    # volumes:
    #   - backend-db:/directus/database
    #   - backend-uploads:/directus/uploads
    #   - backend-logs:/directus/logs
    environment:
      # PM2
      - PM2_LOG_OUT_FILE=/directus/logs/out.log
      - PM2_LOG_ERROR_FILE=/directus/logs/error.log
      # GENERAL
      - LOG_LEVEL
      # SECURITY
      # Initial admin user credentials
      - ADMIN_EMAIL=${ADMIN_EMAIL:?}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:?}
      # If not set, a random value will be used. This means sessions won't persist across restarts or
      # horizontally scaled deployments.
      - SECRET
      - CORS_ENABLED
      - CORS_ORIGIN
      # CACHE
      - CACHE_ENABLED
      # FILE STORAGE
      # Maximum file upload size allowed. For example 10mb, 1gb, 10kb.
      - FILES_MAX_UPLOAD_SIZE
      # AUTHENTICATION
      # See example authentication providers here: https://docs.directus.io/self-hosted/sso-examples.html
      # EMAIL
      - EMAIL_FROM=no-reply@${DOMAIN_NAME:?}
      - EMAIL_TRANSPORT=smtp
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST:?}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:?}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE:-true}
      # WEBSOCKETS
      - WEBSOCKETS_ENABLED
  email:
    image: inbucket/inbucket:latest
    ports:
      - 9000:9000
    profiles:
      - local
volumes:
  backend-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BACKEND_DATABASE_PATH:-/tmp/app_data/backend/database}
  backend-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BACKEND_UPLOADS_PATH:-/tmp/app_data/backend/uploads}
  backend-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${APPLICATION_LOGS_PATH:-/tmp/app_data/logs}
