name: cms-template

services:
    proxy:
        image: jeff2266.engineering/$COMPOSE_PROJECT_NAME-proxy:latest
        build:
            context: ./proxy/
        depends_on:
            frontend:
                condition: service_started
                restart: true
            backend:
                condition: service_started
                restart: true
        ports:
            - 80:80
        environment:
            DOMAIN_NAME: 'localhost'
    frontend:
        image: jeff2266.engineering/$COMPOSE_PROJECT_NAME-frontend:latest
        build:
            context: ./frontend/
        ports:
            - 4321:4321
    backend:
        image: jeff2266.engineering/$COMPOSE_PROJECT_NAME-directus:latest
        build:
            context: ./backend/
        ports:
            - 8055:8055
        environment:
            ADMIN_EMAIL: 'jeff2266@gmail.com'
            ADMIN_PASSWORD: 'P@ssw0rd'
            SECRET: 'replace-with-secure-random-value'
