# Use the official Directus image as the base image
FROM directus/directus:11

# Need to install pm2-logrotate

# Volume permissions


# Copy the migrations directory into the container
COPY migrations /directus/migrations
